import type { Metadata } from "next";

import Sidebar from "@/components/Sidebar";

//import "../css/globals.css";

import "../styles/globals.scss";

import PageTransition from "@/components/PageTransition";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <div className="relative w-full h-screen">
          <PageTransition>{children}</PageTransition>
          <div className="overlay">
            <div className="overlay__bg"></div>
            <div className="overlay__sidebar"><Sidebar /></div>
          </div>
        </div>
      </body>
    </html>
  );
  /*
  return (
    <html lang="en">
      <body className="">
        <div className="relative w-full h-screen">
          <PageTransition>{children}</PageTransition>
          <div className="absolute h-screen bg-black bg-opacity-80 w-2/3 left-0 top-0 bottom-0"></div>
          <div className="app-sidebar absolute w-1/3 h-screen top-0 right-0 bottom-0 flex items-center justify-center">
            <Sidebar />
          </div>
        </div>
      </body>
    </html>
  ); */
}
